simplify, refactor, fix some quirks

diff --git a/libexec/mkradmin/mkradmin-confirm b/libexec/mkradmin/mkradmin-confirm
--- a/libexec/mkradmin/mkradmin-confirm
+++ b/libexec/mkradmin/mkradmin-confirm
@@ -2,7 +2,10 @@
 ### mkradmin-confirm -- confirm a proposed multisig action
 ### Usage: mkradmin confirm <action>
 set -e
-: ${1?missing action identifier}
-mkradmin --ensure-account "${0##*/}"
-echo >&2 "Confirming action $1..."
-seth send @maker_multisig "confirm(uint)" "$1"
+fail() { echo >&2 "${0##*/}: $*"; exit 1; }
+echo "Confirming action ${1?which action?}..."
+
+seth send @mkr_ms "confirm(uint)(bool)" "$1" ||
+fail "error: failed to confirm action $1"
+
+echo "Successfully confirmed action $1."
diff --git a/libexec/mkradmin/mkradmin-propose b/libexec/mkradmin/mkradmin-propose
--- a/libexec/mkradmin/mkradmin-propose
+++ b/libexec/mkradmin/mkradmin-propose
@@ -1,26 +1,27 @@
 #!/usr/bin/env bash
 ### mkradmin-propose -- propose a new multisig action
 ### Usage: mkradmin propose <target> <sig> [<args>]
-###    or: mkradmin propose <target> [<data>]
+###    or: mkradmin propose <target> <data>
 ###
 ### Submit a proposal for the multisig to call <target> with <data>.
-### If <sig> has the form `<name>(<types>)', infer <data> from <args>.
+### If <sig> has the form `<name>(<types>)', then infer <data> from <args>.
 set -e
-[[ $1 ]] || { mkradmin propose --help; exit 1; }
-target=$(seth --to-address "${1?missing target address}")
-data=$(seth calldata ${2+"${@:2}"})
-mkradmin --ensure-account "${0##*/}"
-if ! [[ $MKRADMIN_SILENT ]]; then
-  echo >&2 "Proposing multisig action..."
-  echo >&2 "  receiver   $target"
-  echo >&2 "  calldata   $data"
-fi
+fail() { echo >&2 "${0##*/}: $*"; exit 1; }
+[[ $2 ]] || { mkradmin propose --help; exit 1; }
+
+target=$(seth --to-address "${1?which target address?}")
+calldata=$(seth calldata ${2+"${@:2}"})
+
+cat >&2 <<.
+Proposing multisig action...
+  target     $target
+  calldata   $calldata
+.
+
 sig="propose(address,bytes,uint256)(uint)"
-n=$(seth send @maker_multisig "$sig" "${target#0x}" "${data#0x}" 0)
+n=$(seth send @mkr_ms "$sig" "${target#0x}" "${calldata#0x}" 0)
 n=$(seth --to-dec "$n")
-if [[ $n = 0 ]]; then
-  echo >&2 "${0##*/}: error: failed to create proposal"
-  exit 1
-else
-  echo "Successfully proposed action $n."
-fi
+
+[[ $n -gt 0 ]] || fail "error: failed to create proposal"
+
+echo "Successfully proposed action $n."
diff --git a/libexec/mkradmin/mkradmin-trigger b/libexec/mkradmin/mkradmin-trigger
--- a/libexec/mkradmin/mkradmin-trigger
+++ b/libexec/mkradmin/mkradmin-trigger
@@ -1,28 +1,27 @@
 #!/usr/bin/env bash
-set -e
 ### mkradmin-trigger -- trigger confirmed multisig action
 ### Usage: mkradmin trigger <action>
+set -e
+fail() { echo >&2 "${0##*/}: $*"; exit 1; }
 
-action=$(mkradmin action "${1?missing action identifier}")
-if [[ $(seth --field expired <<<"$action") = true ]]; then
-  echo >&2 "${0##*/}: error: action expired: $1"
-  exit 1
-elif [[ $(seth --field confirmed <<<"$action") = false ]]; then
-  echo >&2 "${0##*/}: error: action not confirmed: $1"
-  exit 1
-elif [[ $(seth --field triggered <<<"$action") = true ]]; then
-  echo >&2 "${0##*/}: error: action already triggered: $1"
-  exit 1
+action=$(mkradmin action "${1?which action?}")
+get() { seth --field "$1" <<<"$action"; }
+
+if [[ $(get expired) = true ]]; then
+  fail "error: action $1 expired"
+elif [[ $(get confirmed) = false ]]; then
+  fail "error: action $1 not confirmed"
+elif [[ $(get triggered) = true ]]; then
+  fail "error: action $1 already triggered"
 fi
 
-echo >&2 "Triggering action $1..."
-seth send @maker_multisig "trigger(uint)" "$1"
+echo "Triggering action $1..."
+seth send @mkr_ms "trigger(uint)" "$1"
 
 action=$(mkradmin action "$1")
-triggered=$(seth --field triggered <<<"$action")
-if [[ $triggered = true ]]; then
-  echo >&2 "Action $1 triggered successfully."
+
+if [[ $(get triggered) = true ]]; then
+  echo "Action $1 successfully triggered."
 else
-  echo >&2 "${0##*/}: error: failed to trigger action"
-  exit 1
+  fail "failed to trigger action $1"
 fi
diff --git a/libexec/mkradmin/mkradmin-verify b/libexec/mkradmin/mkradmin-verify
--- a/libexec/mkradmin/mkradmin-verify
+++ b/libexec/mkradmin/mkradmin-verify
@@ -1,20 +1,44 @@
 #!/usr/bin/env bash
 ### mkradmin-verify -- verify the meaning of a multisig action
 ### Usage: mkradmin verify <tx-hash> <target> <sig> [<args>]
-###    or: mkradmin verify <tx-hash> <target> [<data>]
+###    or: mkradmin verify <tx-hash> <target> <data>
 ###
 ### Verify that <tx-hash> creates a proposal to call <target> with <data>.
 ### If <sig> has the form `<name>(<types>)', infer <data> from <args>.
 set -e
-[[ $2 ]] || { mkradmin verify --help; exit 1; }
-target=$(seth --to-address "${2?missing target address}")
-data=$(seth calldata ${3+"${@:3}"})
-sig="propose(address,bytes,uint256)(uint)"
-expected=$(seth calldata "$sig" "${target#0x}" "${data#0x}" 0)
-actual=$(seth tx "$1" input)
-if diff -U9999 <(fold -w 64 <<<"$expected") <(fold -w 64 <<<"$actual"); then
-  echo "Transaction matches expected calldata."
-else
-  echo >&2 "${0##*/}: error: transaction does not match expected calldata"
-  exit 1
-fi
+fail() { echo >&2 "${0##*/}: $*"; exit 1; }
+[[ $3 ]] || { mkradmin verify --help; exit 1; }
+
+tx=$1
+actual=$(seth tx "$tx" input)
+actual=${actual#0x}
+
+target=$(seth --to-address "$2")
+target=${target#0x}
+calldata=$(seth calldata ${3+"${@:3}"})
+calldata=${calldata#0x}
+inner_sig=$3
+
+sig="propose(address,bytes,uint256)"
+expected=$(seth calldata "$sig" "$target" "$calldata" 0)
+expected=${expected#0x}
+
+explain() {
+  hash=$(seth calldata "$1")
+  hash=${hash#0x}
+  sed "s/$hash/$hash # $1/"
+}
+
+format() {
+  printf %s\\n "${1:0:8}" "${1:8:264}" "${1:272}" | fold -w64 |
+  explain "$sig" | explain "$inner_sig"
+}
+
+actual=$(format "$actual")
+expected=$(format "$expected")
+
+diff -U9999 <(echo "$actual") <(echo "$expected") ||
+fail "error: transaction does not match expected calldata"
+
+echo "$actual"
+echo "Transaction matches expected calldata."
